"use strict";

// ─────────────────────────────────────────────────────────────────────────────
// Тесты фильтра. Каждый кейс: { text, profane, note? }.
//   profane: true  — фильтр ОБЯЗАН поймать (мат, в т.ч. обходы),
//   profane: false — фильтр НЕ ДОЛЖЕН трогать (обычные сообщения).
// Прогоняются кнопкой на странице и через `node run-tests.js`.
// ─────────────────────────────────────────────────────────────────────────────

var FILTER_TESTS = [
  // ── Русский мат: прямые написания ──
  { text: "блядь", profane: true },
  { text: "блять", profane: true },
  { text: "хуй", profane: true },
  { text: "пизда", profane: true },
  { text: "ПИЗДЕЦ", profane: true, note: "верхний регистр" },
  { text: "ебать", profane: true },
  { text: "ёбаный", profane: true, note: "буква ё" },
  { text: "ёб твою мать", profane: true },
  { text: "заебал", profane: true },
  { text: "долбоёб", profane: true },
  { text: "далбаёб", profane: true, note: "безграмотное написание" },
  { text: "выёбывается", profane: true },
  { text: "сука", profane: true },
  { text: "сучка", profane: true },
  { text: "иди нахуй", profane: true },
  { text: "иди на хуй", profane: true, note: "раздельно" },
  { text: "иди нах", profane: true, note: "фразовый корень идинах" },
  { text: "иди нах отсюда", profane: true },
  { text: "пошёл нах", profane: true },
  { text: "idi nah", profane: true, note: "транслит фразы" },
  { text: "нахал и наглец", profane: false, note: "голого корня нах нет" },
  { text: "находка для шпиона", profane: false },
  { text: "охуеть", profane: true },
  { text: "психически охуевший", profane: true, note: "психу в whitelist, но отдельное охуевший ловится" },
  { text: "пидор", profane: true },
  { text: "мудак", profane: true },
  { text: "гандон", profane: true },
  { text: "шлюха", profane: true },
  { text: "залупа", profane: true },
  { text: "спиздили", profane: true, note: "корень внутри слова" },
  { text: "распиздяй", profane: true },
  { text: "объебал", profane: true },
  { text: "отъебись", profane: true },
  { text: "ёбнутый", profane: true },

  // ── Телесная лексика (находки модерации, 2-я итерация) ──
  { text: "пися", profane: true },
  { text: "писька", profane: true },
  { text: "письки", profane: true },
  { text: "писюн", profane: true },
  { text: "пенис", profane: true },
  { text: "penis", profane: true, note: "транслит ловится русским проходом" },
  { text: "сиськи", profane: true },
  { text: "сися", profane: true },
  { text: "сосалка", profane: true },
  { text: "отсосал", profane: true },
  { text: "обкончал", profane: true },
  { text: "накончал", profane: true },
  { text: "кончает", profane: true },
  { text: "сперма", profane: true },
  { text: "sperma", profane: true },
  { text: "гавно", profane: true, note: "безграмотное говно" },
  { text: "в доме, блядь, и накончал в", profane: true, censoredContains: "дом",
    note: "регрессия: «доме бл» слипалось в whitelist-слово «мебл» и глушило «бля»" },

  // ── Русский мат: обходы ──
  { text: "б л я д ь", profane: true, note: "пробелы между буквами — кейс модератора" },
  { text: "б.л.я.д.ь", profane: true, note: "точки" },
  { text: "б-л-я-д-ь", profane: true, note: "дефисы" },
  { text: "б_л_я_д_ь", profane: true, note: "подчёркивания" },
  { text: "бЛяДь", profane: true, note: "смешанный регистр" },
  { text: "бляяяядь", profane: true, note: "повтор букв" },
  { text: "6лядь", profane: true, note: "цифра 6 вместо б" },
  { text: "х у й", profane: true },
  { text: "ху*й", profane: true, note: "символ-вставка" },
  { text: "xyй", profane: true, note: "латинские двойники x, y" },
  { text: "пи3да", profane: true, note: "цифра 3 вместо з" },
  { text: "п и з д а", profane: true },
  { text: "су4ка", profane: true, note: "4 вместо ч" },
  { text: "пид0р", profane: true, note: "0 вместо о" },
  { text: "сmерdи cyka тут", profane: true, note: "смесь латиницы и кириллицы" },

  // ── Русский мат: транслит ──
  { text: "blyad", profane: true },
  { text: "blyat", profane: true },
  { text: "cyka", profane: true },
  { text: "suka", profane: true },
  { text: "pizdec", profane: true },
  { text: "p i z d a", profane: true, note: "транслит + пробелы" },
  { text: "ebat", profane: true },
  { text: "yebat", profane: true },
  { text: "yobany", profane: true },
  { text: "huy", profane: true },
  { text: "hui", profane: true },
  { text: "ohuet", profane: true },
  { text: "pidor", profane: true },
  { text: "shluha", profane: true, note: "sh-диграф" },
  { text: "eblan", profane: true },
  { text: "zaebal", profane: true },

  // ── Английский мат ──
  { text: "fuck", profane: true },
  { text: "f u c k", profane: true, note: "пробелы" },
  { text: "fuсk", profane: true, note: "кириллическая с внутри" },
  { text: "fucking hell", profane: true },
  { text: "sh1t", profane: true, note: "leet: 1 вместо i" },
  { text: "bitch", profane: true },
  { text: "b1tch", profane: true },
  { text: "фак ю", profane: true, note: "русское написание fuck" },
  { text: "asshole", profane: true },
  { text: "pussy", profane: true },

  // ── Другие языки: базовые проверки (de / es / tr / ja) ──
  { text: "fick dich", profane: true },
  { text: "scheiße", profane: true },
  { text: "scheisse", profane: true },
  { text: "arschloch", profane: true },
  { text: "hurensohn", profane: true },
  { text: "du schlampe", profane: true },
  { text: "puta madre", profane: true },
  { text: "hijo de puta", profane: true },
  { text: "eres un cabrón", profane: true },
  { text: "pendejo", profane: true },
  { text: "mierda", profane: true },
  { text: "joder tío", profane: true },
  { text: "gilipollas", profane: true },
  { text: "maricón", profane: true },
  { text: "amk", profane: true },
  { text: "siktir git", profane: true },
  { text: "orospu çocuğu", profane: true },
  { text: "amına koyayım", profane: true },
  { text: "amcık", profane: true },
  { text: "piç kurusu", profane: true },
  { text: "くそ", profane: true },
  { text: "クソゲー", profane: true, note: "знак долготы ー выбрасывается" },
  { text: "死ね", profane: true },
  { text: "まんこ", profane: true },
  { text: "うんこ", profane: true },
  { text: "ファック", profane: true },

  // ── Другие языки: чистые сообщения и ловушки ──
  { text: "computadora nueva", profane: false, note: "comput: содержит puta" },
  { text: "una disputa entre amigos", profane: false },
  { text: "buena reputación", profane: false },
  { text: "input a number", profane: false, note: "input a: слипается в puta" },
  { text: "team kill отменили", profane: false, note: "team k: слипается в amk" },
  { text: "klasik müzik dinle", profane: false, note: "klasik: потому bare sik не корень" },
  { text: "oynayarak öğreniyorum", profane: false, note: "суффикс -yarak: потому yarak не корень" },
  { text: "beni götürmek", profane: false, note: "götürmek: потому göt не корень" },
  { text: "traffic jam", profane: false },
  { text: "sandwiches are tasty", profane: false },
  { text: "office building", profane: false },
  { text: "こんにちは", profane: false },
  { text: "ありがとうございました", profane: false },

  // ── Чистые сообщения (не должны срабатывать) ──
  { text: "привет", profane: false },
  { text: "как пройти уровень?", profane: false },
  { text: "за мной!", profane: false },
  { text: "я тебя люблю", profane: false },
  { text: "команда красных победила", profane: false, note: "команда: корень манд" },
  { text: "командир, жди меня", profane: false },
  { text: "сколько рублей стоит?", profane: false, note: "рублей: корень бля" },
  { text: "застрахуй машину", profane: false, note: "классика: страхуй" },
  { text: "подстрахуй меня на трамплине", profane: false },
  { text: "не буду играть", profane: false, note: "не буду: слипается в ебу" },
  { text: "не балуйся", profane: false },
  { text: "не бывает такого", profane: false },
  { text: "употреблять воду полезно", profane: false },
  { text: "оскорблять нельзя", profane: false },
  { text: "хулиган отобрал мяч", profane: false },
  { text: "барсук в лесу", profane: false },
  { text: "я несу карандаш", profane: false, note: "несу ка: слипается в сука" },
  { text: "мандарин вкусный", profane: false },
  { text: "я психую на этом уровне", profane: false },
  { text: "колебания маятника", profane: false },
  { text: "хлебушек свежий", profane: false },
  { text: "требуется помощь", profane: false },
  { text: "мне нравится учёба", profane: false },
  { text: "у нас дебаты в школе", profane: false },
  { text: "где батарейка?", profane: false },
  { text: "победа за нами", profane: false },
  { text: "небо голубое", profane: false },
  { text: "стебель растения", profane: false },
  { text: "плыли на кораблях", profane: false },
  { text: "сабля острая", profane: false },
  { text: "гребля на байдарках", profane: false },
  { text: "это ребус какой-то", profane: false },
  { text: "опорный прыжок", profane: false },
  { text: "сосиска в тесте", profane: false },
  { text: "сельдь под шубой", profane: false },
  { text: "тут мебель передвинули", profane: false },
  { text: "я закончил уровень", profane: false, note: "закончил ≠ кончал" },
  { text: "они закончат стройку", profane: false },
  { text: "окончательно решил", profane: false },
  { text: "список уровней", profane: false, note: "список: корень писки" },
  { text: "подписка на канал", profane: false },
  { text: "переписка с другом", profane: false },
  { text: "запиши меня в записки", profane: false },
  { text: "он написал сообщение", profane: false },
  { text: "мышка пискнула", profane: false },
  { text: "такое было вчера", profane: false, note: "такое было: слипается в ебы" },
  { text: "всё было быстро", profane: false },
  { text: "уже били по воротам", profane: false },
  { text: "хлебнул воды", profane: false },
  { text: "тебе будет интересно", profane: false, note: "тебе бу: слипается в ебу" },
  { text: "Ощущение, будто в душу плюнули.", profane: false, note: "ние, бу → ебу; гасится стыком ебуд" },
  { text: "ТЫ ЧЁ БЛИН", profane: false, note: "чЁ БЛин → ебл; стык чебли" },
  { text: "ещё блок поставь", profane: false },
  { text: "уже близко финиш", profane: false },
  { text: "чё ёбнутый что ли", profane: true, note: "ё ёб → ебн не должен гаситься" },
  { text: "ты чё, блять", profane: true, note: "бля не должен гаситься стыком чебл*" },
  { text: "чё ебанутый", profane: true },
  { text: "уже блять как достало", profane: true },
  { text: "настроение будет лучше", profane: false },
  { text: "вас всех ебут", profane: true, note: "ебут не должен глушиться стыком ебуд" },
  { text: "две банки колы", profane: false },
  { text: "не бань меня, админ", profane: false },
  { text: "peacock", profane: false },
  { text: "cocktail party", profane: false },
  { text: "fake news", profane: false },
  { text: "such a good game", profane: false },
  { text: "pass the level", profane: false },
  { text: "nigeria", profane: false },

  // ── Английский текст через русский транслит-проход (находки на длинном тексте) ──
  { text: "bringing together 500+ game industry professionals", profane: false, note: "toget-her → хер" },
  { text: "game business leaders", profane: false, note: "game bu → ебу" },
  { text: "Day 2 — Focus & Exchange", profane: false, note: "s ex → sex" },
  { text: "where game industry professionals share real experience", profane: false },
  { text: "here and there", profane: false },
  { text: "the battle begins", profane: false, note: "е bat → ебат" },
  { text: "throw the ball", profane: false, note: "е bal → ебал" },
  { text: "fireball and baseball", profane: false },
  { text: "place the blocks", profane: false, note: "е bl → ебл" },
  { text: "he banned me, we ban cheaters", profane: false, note: "е ban → ебан" },
  { text: "game ban for cheats", profane: false },
  { text: "the elder guardian", profane: false, note: "е eld → елд" },
  { text: "hold the field", profane: false },
  { text: "extra hard mode", profane: false, note: "tra h → трах" },
  { text: "stupid orange", profane: false, note: "pid or → пидор" },
  { text: "command and demand", profane: false },
  { text: "such kind of you", profane: false },
  { text: "his rat is cute", profane: false },
  { text: "so salty association", profane: false },
  { text: "i was hit by the boss hit", profane: false, note: "s hit → shit" },
  { text: "magic until dawn", profane: false, note: "c unt → cunt" },
  { text: "web tools", profane: false },
  { text: "happiness", profane: false },
  { text: "beyblade blade storm", profane: false },
  { text: "а в этом то и есть фишка", profane: false, note: "фишка → fuk при и→u в EN-карте" },
  { text: "фиксировать результат", profane: false },
  { text: "графика и трафик в игре", profane: false },

  // охрана: кириллица и важный транслит после введения nativeRoots
  { text: "хер с ним и херня", profane: true, note: "хер native: кириллицей ловится" },
  { text: "вас ебут", profane: true },
  { text: "манда", profane: true },
  { text: "насрать мне", profane: true },
  { text: "сучка крашена", profane: true },
  { text: "yobany v rot", profane: true, note: "ебан остался не-native ради транслита" },
  { text: "ti che eblan", profane: true },

  // ── Проверка цензуры (звёздочки именно там, где мат) ──
  { text: "иди нахуй отсюда", profane: true, censoredContains: "отсюда" },
  { text: "ты сука понял", profane: true, censoredContains: "понял" }
];

// Прогон тестов. Возвращает { total, passed, failed, results }.
function runFilterTests(filter) {
  var results = [];
  var passed = 0;
  for (var i = 0; i < FILTER_TESTS.length; i++) {
    var tc = FILTER_TESTS[i];
    var r = filter.check(tc.text);
    var ok = r.profane === tc.profane;
    if (ok && tc.censoredContains !== undefined) {
      ok = r.censored.indexOf(tc.censoredContains) !== -1 && r.censored.indexOf("*") !== -1;
    }
    if (ok) passed++;
    results.push({
      text: tc.text,
      note: tc.note || "",
      expected: tc.profane,
      got: r.profane,
      censored: r.censored,
      hits: r.hits,
      ok: ok
    });
  }
  return { total: FILTER_TESTS.length, passed: passed, failed: FILTER_TESTS.length - passed, results: results };
}

// Для node-раннера тестов (в браузере просто игнорируется).
if (typeof module !== "undefined" && module.exports) {
  module.exports = { FILTER_TESTS: FILTER_TESTS, runFilterTests: runFilterTests };
}
