@echo off
rem Local check of the C# port without Unity: compiles the core + runner and
rem runs the test corpus (tests.txt is generated by: node export-unity-data.js).
cd /d "%~dp0"
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe /nologo /out:RunTests.exe RunTests.cs "..\unity\ProfanityFilter\ProfanityFilter.cs" || exit /b 1
.\RunTests.exe
